name: pylint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: snok/install-poetry@v1
      - run: poetry install
      - run: poetry run pylint src/blossom
