name: publish-releases

on:
  release:
    types: [published]

jobs:
  build-source-dist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools
          python -m pip install build

      - name: Build the package
        run: python -m build

      - name: Upload source distribution
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882
        with:
          name: "awesom-sdist"
          path: dist/

  pypi-publish:
    name: Upload releases to PyPI
    needs: [build-source-dist]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/awesom
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Retrieve all artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
        with:
          path: ./dist
      - name: Prepare artifacts
        run:  ls -R ./dist
      - name: Upload files
        uses: pypa/gh-action-pypi-publish@f7600683efdcb7656dec5b29656edb7bc586e597
