name: test

on: [push]

jobs:
  run-unittests:
    strategy:
      matrix:
        platform: ["macos-latest", "windows-latest", "ubuntu-latest"]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: |
            3.10
            3.11
      - run: python3 -m pip install --user pipx
      - run: python3 -m pipx ensurepath
      - run: pipx install tox
      - run: tox r
